USE `hack_kuet`;

UPDATE `blogs` SET
  `content` = 'Most MCU problems are not dramatic. The board is often just underpowered, held in the wrong boot mode, or wired in a way that hides the real issue. We tell new builders to confirm power first, then reset and clock behavior, and only then move on to firmware upload or peripheral debugging.\n\nAnother common mistake is trusting the example circuit without checking the board in front of you. Real wiring has resistance, and real student projects have loose headers, swapped cables, and connectors plugged in one row off. The quickest way to find those issues is to compare the board against a known-good reference and measure at the board, not at the supply.\n\nThe point is not to make beginners memorize every failure mode. The point is to give them a repeatable order of checks so they can stop guessing.'
WHERE `slug` = 'mcu-mistakes';

UPDATE `blogs` SET
  `content` = 'Our first pass is electrical. We check every power net, confirm the current path is realistic, and make sure trace widths match the load. If the board carries motors or other noisy loads, we verify the return path too. A clean schematic is not enough if the layout forces current to take a bad route.\n\nThe second pass is mechanical. That is where connector orientation, mounting holes, and silkscreen labels matter. If a connector can be flipped by accident, we fix that before fabrication. If a header is hidden under another part, we ask whether the assembly step will still be practical in a student lab with limited tools.\n\nThe final pass is boring but valuable: compare the BOM, footprints, and schematic pin numbers line by line. That is where swapped pads and mismatched package names usually show up.'
WHERE `slug` = 'pcb-review-checklist';

UPDATE `blogs` SET
  `content` = 'The fastest way to understand a noisy sensor is to measure the raw output before filtering anything in code. If the signal is unstable at the pin, the problem is usually wiring, grounding, or power quality. We look for loose jumpers, long leads, and shared supply paths that let one device disturb another.\n\nOnce the hardware looks sane, we focus on sampling. A bad sample rate can make a stable signal look chaotic, and a weak filter can hide the actual shape of the data. We prefer short, direct tests that isolate one variable at a time. That keeps us from guessing when the issue is really the timing window or the sensor''s response curve.\n\nWhen the lab is noisy, the best fix is often simple: shorten the cable, add a ground reference, and give the sensor a cleaner power rail. Those changes are not exciting, but they usually do more than a complicated algorithm that is trying to rescue bad input.'
WHERE `slug` = 'sensor-noise-debugging';

UPDATE `blogs` SET
  `content` = 'We tune in stages. First we check that the sensors read cleanly and the robot can follow the line at a very low gain. Then we increase proportional response until the robot reacts quickly, but not so aggressively that it starts to swing back and forth after every correction.\n\nOnce the base response is stable, we add only a small amount of integral correction. That part is easy to overdo, especially when the test track is too clean. In real runs, battery voltage drifts, the floor changes, and the robot sees slightly different reflectance every lap. The controller has to survive that, not just a perfect demo table.\n\nWe keep derivative gain conservative. If the hardware is already vibrating or the sensor reads with a bit of delay, too much D gain just makes the system chase noise. The best results usually come from a controller that is slightly less clever and much more predictable.'
WHERE `slug` = 'pid-tuning';

UPDATE `blogs` SET
  `content` = 'We split firmware into three layers. Drivers do the hardware-specific work. Services turn raw reads and writes into stable, meaningful operations. The application layer decides what the machine should do next. That separation keeps behavior predictable and makes it much easier for new members to understand where a change belongs.\n\nThe reason this works is that each layer has a narrow job. Drivers should not know about team strategy, and the application should not care which register a sensor uses. That rule keeps code review focused. If a change crosses layers, we stop and ask whether the interface is doing too much.\n\nWe also keep naming strict. A function should explain what it does without a long comment. A module should make its dependencies obvious.'
WHERE `slug` = 'firmware-architecture';

UPDATE `blogs` SET
  `content` = 'We start by cutting the project down to one clear story. What should the audience see first? What should happen next? What can fail without breaking the demonstration? Once that is defined, we assign owners for the hardware, firmware, and presentation pieces so everyone knows where they are accountable.\n\nThe middle of the sprint is all about integration. This is where hidden problems show up: power issues, loose connectors, timing mismatches, and assumptions that sounded fine in planning but do not survive real hardware. We keep a simplified demo mode and a fallback power path so the team can recover quickly if something misbehaves during rehearsal.\n\nThe final step is rehearsal under time pressure. That is when we find out whether the story is clear, whether the setup is repeatable, and whether the team can recover without panic.'
WHERE `slug` = 'demo-day-sprint';

